using System.Text;

namespace Ps1Forge.Core;

public static class Ps1ConfigBuilder
{
    public static string Build(string titleId, string region)
    {
        // Match the PSX-FPKG v0.3 PS1HD template. Game identity belongs in
        // PARAM.SFO/CONTENT_ID; the emulator config only selects the disc and
        // user-facing emulator options.
        var b = new StringBuilder();
        b.AppendLine("#Generated by Ps1Forge");
        b.AppendLine("--ps4-trophies = 0");
        b.AppendLine("--ps5-uds=0");
        b.AppendLine("--trophies=0");
        b.AppendLine("--image=\"data/disc1.bin\"");
        b.AppendLine();
        b.AppendLine("#PS1HD template options");
        b.AppendLine("--scale=6");
        b.AppendLine("--bios-hide-sce-osd=1");
        return b.ToString();
    }
}
